package com.revent.util;

import org.bukkit.Material;

import java.util.Arrays;
import java.util.List;

public class MaterialGroups {

	//----------------TOOLS
	public static final List<String> SHOVEL = Arrays.asList( "WOODEN_SHOVEL", "STONE_SHOVEL", "IRON_SHOVEL", "GOLDEN_SHOVEL", "DIAMOND_SHOVEL" );

	public static final List<String> PICKAXE = Arrays.asList( "WOODEN_PICKAXE", "STONE_PICKAXE", "IRON_PICKAXE", "GOLDEN_PICKAXE", "DIAMOND_PICKAXE" );

	public static final List<String> AXE = Arrays.asList( "WOODEN_AXE", "STONE_AXE", "IRON_AXE", "GOLDEN_AXE", "DIAMOND_AXE" );

	public static final List<String> HOE = Arrays.asList( "WOODEN_HOE", "STONE_HOE", "IRON_HOE", "GOLDEN_HOE", "DIAMOND_HOE" );

	public static final List<String> SWORD = Arrays.asList( "WOODEN_SWORD", "STONE_SWORD", "IRON_SWORD", "GOLDEN_SWORD", "DIAMOND_SWORD" );
	//----------------TOOLS

	//----------------DOORS
	public static final List<String> WOODTRAPDOOR = Arrays.asList("DARK_OAK_TRAPDOOR", "BIRCH_TRAPDOOR", "ACACIA_TRAPDOOR", "OAK_TRAPDOOR", "SPRUCE_TRAPDOOR", "JUNGLE_TRAPDOOR" );

	public static final List<String> TRAPDOOR = Arrays.asList("IRON_TRAPDOOR", "DARK_OAK_TRAPDOOR", "BIRCH_TRAPDOOR", "ACACIA_TRAPDOOR", "OAK_TRAPDOOR", "SPRUCE_TRAPDOOR", "JUNGLE_TRAPDOOR" );

	public static final List<String> DOOR = Arrays.asList("IRON_DOOR", "ACACIA_DOOR", "BIRCH_DOOR", "DARK_OAK_DOOR", "JUNGLE_DOOR", "OAK_DOOR", "SPRUCE_DOOR");

	public static final List<String> WOODDOOR = Arrays.asList("ACACIA_DOOR", "BIRCH_DOOR", "DARK_OAK_DOOR", "JUNGLE_DOOR", "OAK_DOOR", "SPRUCE_DOOR");
	//----------------DOORS

	//----------------COLORS
	public static final List<String> STAINED_GLASS = Arrays.asList("BLACK_STAINED_GLASS", "WHITE_STAINED_GLASS", "ORANGE_STAINED_GLASS", "BLUE_STAINED_GLASS", "CYAN_STAINED_GLASS", "RED_STAINED_GLASS", "PINK_STAINED_GLASS", "LIME_STAINED_GLASS", "GREEN_STAINED_GLASS", "PURPLE_STAINED_GLASS", "GRAY_STAINED_GLASS", "LIGHT_GRAY_STAINED_GLASS", "LIGHT_BLUE_STAINED_GLASS", "BROWN_STAINED_GLASS", "YELLOW_STAINED_GLASS", "MAGNETA_STAINED_GLASS");

	public static final List<String> STAINED_GLASS_PANE = Arrays.asList("BLACK_STAINED_GLASS_PANE", "WHITE_STAINED_GLASS_PANE", "ORANGE_STAINED_GLASS_PANE", "BLUE_STAINED_GLASS_PANE", "CYAN_STAINED_GLASS_PANE", "RED_STAINED_GLASS_PANE", "PINK_STAINED_GLASS_PANE", "LIME_STAINED_GLASS_PANE", "GREEN_STAINED_GLASS_PANE", "PURPLE_STAINED_GLASS_PANE", "GRAY_STAINED_GLASS_PANE", "LIGHT_GRAY_STAINED_GLASS_PANE", "LIGHT_BLUE_STAINED_GLASS_PANE", "BROWN_STAINED_GLASS_PANE", "YELLOW_STAINED_GLASS_PANE", "MAGNETA_STAINED_GLASS_PANE");

	public static final List<String> BANNER = Arrays.asList("BLACK_BANNER", "WHITE_BANNER", "ORANGE_BANNER", "BLUE_BANNER", "CYAN_BANNER", "RED_BANNER", "PINK_BANNER", "LIME_BANNER", "GREEN_BANNER", "PURPLE_BANNER", "GRAY_BANNER", "LIGHT_GRAY_BANNER", "LIGHT_BLUE_BANNER", "BROWN_BANNER", "YELLOW_BANNER", "MAGNETA_BANNER");

	public static final List<String> BED = Arrays.asList("BLACK_BED", "WHITE_BED", "ORANGE_BED", "BLUE_BED", "CYAN_BED", "RED_BED", "PINK_BED", "LIME_BED", "GREEN_BED", "PURPLE_BED", "GRAY_BED", "LIGHT_GRAY_BED", "LIGHT_BLUE_BED", "BROWN_BED", "YELLOW_BED", "MAGNETA_BED");

	public static final List<String> CARPET = Arrays.asList("BLACK_CARPET", "WHITE_CARPET", "ORANGE_CARPET", "BLUE_CARPET", "CYAN_CARPET", "RED_CARPET", "PINK_CARPET", "LIME_CARPET", "GREEN_CARPET", "PURPLE_CARPET", "GRAY_CARPET", "LIGHT_GRAY_CARPET", "LIGHT_BLUE_CARPET", "BROWN_CARPET", "YELLOW_CARPET", "MAGNETA_CARPET");

	public static final List<String> CONCRETE = Arrays.asList("BLACK_CONCRETE", "WHITE_CONCRETE", "ORANGE_CONCRETE", "BLUE_CONCRETE", "CYAN_CONCRETE", "RED_CONCRETE", "PINK_CONCRETE", "LIME_CONCRETE", "GREEN_CONCRETE", "PURPLE_CONCRETE", "GRAY_CONCRETE", "LIGHT_GRAY_CONCRETE", "LIGHT_BLUE_CONCRETE", "BROWN_CONCRETE", "YELLOW_CONCRETE", "MAGNETA_CONCRETE");

	public static final List<String> CONCRETE_POWDER = Arrays.asList("BLACK_CONCRETE_POWDER", "WHITE_CONCRETE_POWDER", "ORANGE_CONCRETE_POWDER", "BLUE_CONCRETE_POWDER", "CYAN_CONCRETE_POWDER", "RED_CONCRETE_POWDER", "PINK_CONCRETE_POWDER", "LIME_CONCRETE_POWDER", "GREEN_CONCRETE_POWDER", "PURPLE_CONCRETE_POWDER", "GRAY_CONCRETE_POWDER", "LIGHT_GRAY_CONCRETE_POWDER", "LIGHT_BLUE_CONCRETE_POWDER", "BROWN_CONCRETE_POWDER", "YELLOW_CONCRETE_POWDER", "MAGNETA_CONCRETE_POWDER");

	public static final List<String> DYE = Arrays.asList("INK_SAC", "BONE_MEAL", "ORANGE_DYE", "LAPIS_LAZULI", "CYAN_DYE", "ROSE_RED", "PINK_DYE", "LIME_DYE", "CACTUS_GREEN", "PURPLE_DYE", "GRAY_DYE", "LIGHT_GRAY_DYE", "LIGHT_BLUE_DYE", "COCOA_BEANS", "DANDELION_YELLOW", "MAGNETA_DYE");

	public static final List<String> GLAZED_TERRACOTTA = Arrays.asList("BLACK_GLAZED_TERRACOTTA", "WHITE_GLAZED_TERRACOTTA", "ORANGE_GLAZED_TERRACOTTA", "BLUE_GLAZED_TERRACOTTA", "CYAN_GLAZED_TERRACOTTA", "RED_GLAZED_TERRACOTTA", "PINK_GLAZED_TERRACOTTA", "LIME_GLAZED_TERRACOTTA", "GREEN_GLAZED_TERRACOTTA", "PURPLE_GLAZED_TERRACOTTA", "GRAY_GLAZED_TERRACOTTA", "LIGHT_GRAY_GLAZED_TERRACOTTA", "LIGHT_BLUE_GLAZED_TERRACOTTA", "BROWN_GLAZED_TERRACOTTA", "YELLOW_GLAZED_TERRACOTTA", "MAGNETA_GLAZED_TERRACOTTA");

	public static final List<String> SHULKER_BOX = Arrays.asList("BLACK_SHULKER_BOX", "WHITE_SHULKER_BOX", "ORANGE_SHULKER_BOX", "BLUE_SHULKER_BOX", "CYAN_SHULKER_BOX", "RED_SHULKER_BOX", "PINK_SHULKER_BOX", "LIME_SHULKER_BOX", "GREEN_SHULKER_BOX", "PURPLE_SHULKER_BOX", "GRAY_SHULKER_BOX", "LIGHT_GRAY_SHULKER_BOX", "LIGHT_BLUE_SHULKER_BOX", "BROWN_SHULKER_BOX", "YELLOW_SHULKER_BOX", "MAGNETA_SHULKER_BOX");

	public static final List<String> TERRACOTA = Arrays.asList("BLACK_TERRACOTTA", "WHITE_TERRACOTTA", "ORANGE_TERRACOTTA", "BLUE_TERRACOTTA", "CYAN_TERRACOTTA", "RED_TERRACOTTA", "PINK_TERRACOTTA", "LIME_TERRACOTTA", "GREEN_TERRACOTTA", "PURPLE_TERRACOTTA", "GRAY_TERRACOTTA", "LIGHT_GRAY_TERRACOTTA", "LIGHT_BLUE_TERRACOTTA", "BROWN_TERRACOTTA", "YELLOW_TERRACOTTA", "MAGNETA_TERRACOTTA");

	public static final List<String> WOOL = Arrays.asList("BLACK_WOOL", "WHITE_WOOL", "ORANGE_WOOL", "BLUE_WOOL", "CYAN_WOOL", "RED_WOOL", "PINK_WOOL", "LIME_WOOL", "GREEN_WOOL", "PURPLE_WOOL", "GRAY_WOOL", "LIGHT_GRAY_WOOL", "LIGHT_BLUE_WOOL", "BROWN_WOOL", "YELLOW_WOOL", "MAGNETA_WOOL");

	public static final List<String> WHITE = Arrays.asList("WHITE_STAINED_GLASS", "WHITE_WOOL", "WHITE_TERRACOTTA", "WHITE_SHULKER_BOX", "WHITE_GLAZED_TERRACOTTA", "BONE_MEAL", "WHITE_STAINED_GLASS_PANE", "WHITE_BANNER", "WHITE_BED", "WHITE_CARPET", "WHITE_CONCRETE", "WHITE_CONCRETE_POWDER");

	public static final List<String> ORANGE = Arrays.asList("ORANGE_STAINED_GLASS", "ORANGE_WOOL", "ORANGE_STAINED_GLASS_PANE", "ORANGE_TERRACOTTA", "ORANGE_SHULKER_BOX", "ORANGE_BANNER", "ORANGE_BED", "ORANGE_CARPET", "ORANGE_CONCRETE", "ORANGE_CONCRETE_POWDER", "ORANGE_GLAZED_TERRACOTTA", "ORANGE_DYE");

	public static final List<String> BLUE = Arrays.asList("BLUE_GLASS", "BLUE_WOOL", "BLUE_GLASS_PANE", "BLUE_TERRACOTTA", "BLUE_SHULKER_BOX", "BLUE_BANNER", "BLUE_BED", "BLUE_CARPET", "BLUE_CONCRETE", "BLUE_CONCRETE_POWDER", "BLUE_GLAZED_TERRACOTTA", "LAPIS_LAZULI");

	public static final List<String> CYAN = Arrays.asList("CYAN_GLASS", "CYAN_WOOL", "CYAN_GLASS_PANE", "CYAN_TERRACOTTA", "CYAN_SHULKER_BOX", "CYAN_BANNER", "CYAN_BED", "CYAN_CARPET", "CYAN_CONCRETE", "CYAN_CONCRETE_POWDER", "CYAN_GLAZED_TERRACOTTA", "CYAN_DYE");

	public static final List<String> RED = Arrays.asList("RED_GLASS", "RED_WOOL", "RED_GLASS_PANE", "RED_TERRACOTTA", "RED_SHULKER_BOX", "RED_BANNER", "RED_BED", "RED_CARPET", "RED_CONCRETE", "RED_CONCRETE_POWDER", "RED_GLAZED_TERRACOTTA", "ROSE_RED");

	public static final List<String> PINK = Arrays.asList("PINK_GLASS", "PINK_WOOL", "PINK_GLASS_PANE", "PINK_TERRACOTTA", "PINK_SHULKER_BOX", "PINK_BANNER", "PINK_BED", "PINK_CARPET", "PINK_CONCRETE", "PINK_CONCRETE_POWDER", "PINK_GLAZED_TERRACOTTA", "PINK_DYE");

	public static final List<String> LIME = Arrays.asList("LIME_GLASS", "LIME_WOOL", "LIME_GLASS_PANE", "LIME_TERRACOTTA", "LIME_SHULKER_BOX", "LIME_BANNER", "LIME_BED", "LIME_CARPET", "LIME_CONCRETE", "LIME_CONCRETE_POWDER", "LIME_GLAZED_TERRACOTTA", "LIME_DYE");

	public static final List<String> GREEN = Arrays.asList("GREEN_GLASS", "GREEN_WOOL", "GREEN_GLASS_PANE", "GREEN_TERRACOTTA", "GREEN_SHULKER_BOX", "GREEN_BANNER", "GREEN_BED", "GREEN_CARPET", "GREEN_CONCRETE", "GREEN_CONCRETE_POWDER", "GREEN_GLAZED_TERRACOTTA", "CACTUS_GREEN");

	public static final List<String> PURPLE = Arrays.asList("PURPLE_GLASS", "PURPLE_WOOL", "PURPLE_GLASS_PANE", "PURPLE_TERRACOTTA", "PURPLE_SHULKER_BOX", "PURPLE_BANNER", "PURPLE_BED", "PURPLE_CARPET", "PURPLE_CONCRETE", "PURPLE_CONCRETE_POWDER", "PURPLE_GLAZED_TERRACOTTA", "PURPLE_DYE");

	public static final List<String> GRAY = Arrays.asList("GRAY_GLASS", "GRAY_WOOL", "GRAY_GLASS_PANE", "GRAY_TERRACOTTA", "GRAY_SHULKER_BOX", "GRAY_BANNER", "GRAY_BED", "GRAY_CARPET", "GRAY_CONCRETE", "GRAY_CONCRETE_POWDER", "GRAY_GLAZED_TERRACOTTA", "GRAY_DYE");

	public static final List<String> LIGHT_GRAY = Arrays.asList("LIGHT_GRAY_GLASS", "LIGHT_GRAY_WOOL", "LIGHT_GRAY_GLASS_PANE", "LIGHT_GRAY_TERRACOTTA", "LIGHT_GRAY_SHULKER_BOX", "LIGHT_GRAY_BANNER", "LIGHT_GRAY_BED", "LIGHT_GRAY_CARPET", "LIGHT_GRAY_CONCRETE", "LIGHT_GRAY_CONCRETE_POWDER", "LIGHT_GRAY_GLAZED_TERRACOTTA", "LIGHT_GRAY_DYE");

	public static final List<String> LIGHT_BLUE = Arrays.asList("LIGHT_BLUE_GLASS", "LIGHT_BLUE_WOOL", "LIGHT_BLUE_GLASS_PANE", "LIGHT_BLUE_TERRACOTTA", "LIGHT_BLUE_SHULKER_BOX", "LIGHT_BLUE_BANNER", "LIGHT_BLUE_BED", "LIGHT_BLUE_CARPET", "LIGHT_BLUE_CONCRETE", "LIGHT_BLUE_CONCRETE_POWDER", "LIGHT_BLUE_GLAZED_TERRACOTTA", "LIGHT_BLUE_DYE");

	public static final List<String> BROWN = Arrays.asList("BROWN_GLASS", "BROWN_WOOL", "BROWN_GLASS_PANE", "BROWN_TERRACOTTA", "BROWN_SHULKER_BOX", "BROWN_BANNER", "BROWN_BED", "BROWN_CARPET", "BROWN_CONCRETE", "BROWN_CONCRETE_POWDER", "BROWN_GLAZED_TERRACOTTA", "COCOA_BEANS");

	public static final List<String> YELLOW = Arrays.asList("YELLOW_GLASS", "YELLOW_WOOL", "YELLOW_GLASS_PANE", "YELLOW_TERRACOTTA", "YELLOW_SHULKER_BOX", "YELLOW_BANNER", "YELLOW_BED", "YELLOW_CARPET", "YELLOW_CONCRETE", "YELLOW_CONCRETE_POWDER", "YELLOW_GLAZED_TERRACOTTA", "DANDELION_YELLOW");

	public static final List<String> MAGNETA = Arrays.asList("MAGNETA_GLASS", "MAGNETA_WOOL", "MAGNETA_GLASS_PANE", "MAGNETA_TERRACOTTA", "MAGNETA_SHULKER_BOX", "MAGNETA_BANNER", "MAGNETA_BED", "MAGNETA_CARPET", "MAGNETA_CONCRETE", "MAGNETA_CONCRETE_POWDER", "MAGNETA_GLAZED_TERRACOTTA", "MAGNETA_DYE");

	public static final List<String> BLACK = Arrays.asList("BLACK_GLASS", "BLACK_WOOL", "BLACK_GLASS_PANE", "BLACK_TERRACOTTA", "BLACK_SHULKER_BOX", "BLACK_BANNER", "BLACK_BED", "BLACK_CARPET", "BLACK_CONCRETE", "BLACK_CONCRETE_POWDER", "BLACK_GLAZED_TERRACOTTA", "INK_SACK");
	//----------------COLORS

	//----------------ARMOR
	public static final List<String> ARMOR = Arrays.asList("CHAINMAIL_HELMET", "CHAINMAIL_CHESTPLATE", "CHAINMAIL_LEGGINGS", "CHAINMAIL_BOOTS", "CHAINMAIL_HELMET", "CHAINMAIL_CHESTPLATE", "CHAINMAIL_LEGGINGS", "CHAINMAIL_BOOTS", "IRON_HELMET", "IRON_CHESTPLATE", "IRON_LEGGINGS", "IRON_BOOTS", "LEATHER_HELMET", "LEATHER_CHESTPLATE", "LEATHER_LEGGINGS", "LEATHER_BOOTS", "GOLD_HELMET", "GOLD_CHESTPLATE", "GOLD_LEGGINGS", "GOLD_BOOTS", "DIAMOND_HELMET", "DIAMOND_CHESTPLATE", "DIAMOND_LEGGINGS", "DIAMOND_BOOTS");

	public static final List<String> CHAINMAIL_ARMOR = Arrays.asList("CHAINMAIL_HELMET", "CHAINMAIL_CHESTPLATE", "CHAINMAIL_LEGGINGS", "CHAINMAIL_BOOTS");

	public static final List<String> IRON_ARMOR = Arrays.asList("IRON_HELMET", "IRON_CHESTPLATE", "IRON_LEGGINGS", "IRON_BOOTS");

	public static final List<String> LEATHER_ARMOR = Arrays.asList("LEATHER_HELMET", "LEATHER_CHESTPLATE", "LEATHER_LEGGINGS", "LEATHER_BOOTS");

	public static final List<String> GOLD_ARMOR = Arrays.asList("GOLD_HELMET", "GOLD_CHESTPLATE", "GOLD_LEGGINGS", "GOLD_BOOTS");

	public static final List<String> DIAMOND_ARMOR = Arrays.asList("DIAMOND_HELMET", "DIAMOND_CHESTPLATE", "DIAMOND_LEGGINGS", "DIAMOND_BOOTS");

	public static final List<String> HELMET = Arrays.asList("LEATHER_HELMET", "IRON_HELMET", "CHAINMAIL_HELMET", "GOLD_HELMET", "DIAMOND_HELMET");

	public static final List<String> CHESTPLATE = Arrays.asList("LEATHER_CHESTPLATE", "IRON_CHESTPLATE", "CHAINMAIL_CHESTPLATE", "GOLD_CHESTPLATE", "DIAMOND_CHESTPLATE");

	public static final List<String> LEGGINGS = Arrays.asList("LEATHER_LEGGINGS", "IRON_LEGGINGS", "CHAINMAIL_LEGGINGS", "GOLD_LEGGINGS", "DIAMOND_LEGGINGS");

	public static final List<String> BOOTS = Arrays.asList("LEATHER_BOOTS", "IRON_BOOTS", "CHAINMAIL_BOOTS", "GOLD_BOOTS", "DIAMOND_BOOTS");
	//----------------ARMOR

	//----------------EFFECTS
	public static final String[] POTIONEFFECTS = {"ABSORPTION", "BLINDNESS", "CONDUIT_POWER", "CONFUSION", "DAMAGE_RESISTANCE", "DOLPHINS_GRACE", "FAST_DIGGING", "FIRE_RESISTANCE", "GLOWING", "HARM", "HEAL", "HEALTH_BOOST", "HUNGER", "INCREASE_DAMAGE", "INVISIBILITY", "JUMP", "LEVITATION", "LUCK", "NIGHT_VISION", "POISON", "REGENERATION", "SATURATION", "SLOW", "SLOW_DIGGING", "SLOW_FALLING", "SPEED", "UNLUCK", "WATER_BREATHING", "WEAKNESS", "WITHER"};
	//----------------EFFECTS
	private void test() {
		// public static final List<String> s = Arrays.asList("");
	}

	public static String toolsGroup(Material tool) {
		String toolString = tool.toString();
		return SHOVEL.contains(toolString) ? "SHOVEL" : PICKAXE.contains(toolString) ? "PICKAXE" : AXE.contains(toolString) ? "AXE" : HOE.contains(toolString) ? "HOE" : SWORD.contains(toolString) ? "SWORD" : toolString;
	}

	public static String armorGroup(Material armor) {
		String armorString = armor.toString();
		return LEATHER_ARMOR.contains(armorString) ? "LEATHER_ARMOR" : IRON_ARMOR.contains(armorString) ? "IRON_ARMOR" : CHAINMAIL_ARMOR.contains(armorString) ? "CHAINMAIL_ARMOR" : GOLD_ARMOR.contains(armorString) ? "GOLD_ARMOR" : DIAMOND_ARMOR.contains(armorString) ? "DIAMOND_ARMOR" : "armorString";
	}

	public static String armorTypeGroup(Material armor) {
		String armorString = armor.toString();
		return HELMET.contains(armorString) ? "HELMET" : CHESTPLATE.contains(armorString) ? "CHESTPLATE" : LEGGINGS.contains(armorString) ? "LEGGINGS" : BOOTS.contains(armorString) ? "BOOTS" : armorString;
	}
}
